# This is a basic workflow to help you get started with Actions

name: CI-CD-pipeline-AWS-beanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME : "galym-flask-app-packages"
  EB_APPLICATION_NAME       : "myFlask"
  EB_ENVIRONMENT            : "myFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip
  AWS_REGION_NAME           : "us-west-2"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  myCI-part:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git clone our repo
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        

